
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels: 
    app: nginx
    layer: web
    version: "1.25"
spec:
  minReadySeconds: 1
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        versions: "1.25" 
    spec:
      containers:
        - name: nginx 
          image: nginx:1.25
          command: ["/bin/bash", "-c", 'echo this is devops >/usr/share/nginx/html/index.html && sleep 1d']
          ports:
            - containerPort: 80
                  