---
apiVersion: v1
kind: service
metadata:
  name: nginx-svc
spec:
  selector:
    app: dev
  ports:
    - name: svc
      port: 80
      targetPort: nginx-svc
      protocol: TCP
  type: NodePort    
