---
apiVersion: v1
kind: port
metadata: 
  name: exer4
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerport: 80
    - name: httpd
      image: httpd
      ports:
        - containerport: 80


   
