---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-config-env
spec:
  volumes:
    - name: config
      configMap:
        name: dummy-cm
  containers:
    - volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html
      name: alpine
      image: nginx
      ports:
        - name: nginx-svc
          containerPort: 80 