---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  minReadySeconds: 1
  replicas: 8
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        ver: "1.25"
    spec:
      containers: 
       - name: nginx
         image: batchusivaji/devops:v1.0
         ports:
           - ContainerPort: 80

---
apiVersion: v1
kind: service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  ports:
    - name: nginx-svc
      port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort

          
      
