---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nopcommerce-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nop-commerce
  template:
    metadata:
      labels:
        app: nop-commerce
    spec:
      containers:
        - name: nop-commerce
          image: nop-commerce/nop-commerce
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nopcommerce-service
spec: 
  selector:
    app: nopcommerce
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort:80             

               