---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nopcommerce-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nopcommerce
  template:
    metadata:
      labels:
        app: nopcommerce
    spec:
      containers:
        - name: nopcommerce
          image: babunaga/nopcommerce:1.0
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: nopcommerce-service
spec: 
  selector:
    app: nopcommerce
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80             

               