---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: https-rs
spec:
  minReadySeconds: 1
  replicas: 5
  selector:
    matchLabels:
      app: qa
  template: 
    metadata:
      name: httpd
      labels:
        app: qa
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80

