---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: qa
spec:
  containers:
    - image: jenkins/jenkins
      name: jenkins
      ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app: qa
spec:
  containers:
    - image: jenkins/jenkins
      name: jenkins
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  labels:
    app: qa
spec:
  containers:
    - image: jenkins/jenkins
      name: jenkins
      ports:
        - containerPort: 8080
      
